const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Tilemap2: 0},
	{Tilemap3: 0},
	{Vidas: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{player: 0},
	{Teclado: 0},
	{Direction: 0},
	{polvo: 0},
	{Sensor_polvoD: 0},
	{Sensor_polvoE: 0},
	{Mosaico: 0},
	{Âncora: 0},
	{vidas: 0},
	{Audio: 0},
	{Mosaico2: 0},
	{Mouse: 0},
	{Mosaico3: 0},
	{DanoQueda: 0},
	{Portal: 0},
	{Logo: 0},
	{Play: 0},
	{GameOver: 0},
	{Menu: 0},
	{Sprite2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Texto: 0},
	{Sprite: 0},
	{Vida: 0}
];

self.InstanceType = {
	Tilemap2: class extends self.ITilemapInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	polvo: class extends self.ISpriteInstance {},
	Sensor_polvoD: class extends self.ISpriteInstance {},
	Sensor_polvoE: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	vidas: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Mouse: class extends self.IInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	DanoQueda: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {}
}